# Services Collection
# Service cards displayed on the homepage
- name: 'services'
  label: 'Services'
  label_singular: 'Service'
  folder: 'src/content/services'
  create: true
  delete: true
  slug: '{{order}}-{{slug}}'
  identifier_field: 'title'
  sortable_fields: ['order', 'title']
  summary: '{{order}}. {{title}}'
  editor:
    preview: false
  fields:
    - { label: 'Service Title', name: 'title', widget: 'string', hint: 'The name of the service' }
    - { label: 'Description', name: 'description', widget: 'text', hint: 'Brief description of the service' }
    - {
        label: 'Anchor ID',
        name: 'anchor',
        widget: 'string',
        pattern: ['^[a-z0-9-]+$', 'Must be lowercase letters, numbers, and hyphens only'],
        hint: 'URL anchor for linking to this service on the services page (e.g., "adhd-adults")',
      }
    - {
        label: 'Display Order',
        name: 'order',
        widget: 'number',
        default: 1,
        value_type: 'int',
        min: 1,
        hint: 'Order in which this service appears (1 = first)',
      }
    - {
        label: 'Icon',
        name: 'icon',
        widget: 'select',
        required: false,
        options:
          ['tabler:brain', 'tabler:puzzle', 'tabler:clipboard-check', 'tabler:briefcase', 'tabler:heart-handshake'],
        hint: 'Optional icon for the service card',
      }
    - {
        label: 'Published',
        name: 'published',
        widget: 'boolean',
        default: true,
        hint: 'Whether this service is visible on the site',
      }
