# netlify-autism.toml
[build]
  command = "npm run build:autism"
  publish = "dist"

[build.environment]
  SITE_ID = "autism"
  ASSESSMENTS_URL = "https://togetherassessments.co.uk"
  ADHD_URL = "https://togetheradhd.co.uk"
  AUTISM_URL = "https://togetherautism.co.uk"
