site:
  name: Together Assessments
  email: info@togetherassessments.co.uk
  ico_registration: '00010615323'

logo:
  light: ~/assets/images/logo-light.svg
  dark: ~/assets/images/logo-dark.svg
  alt: Together Assessments Logo

hero:
  image: ~/assets/images/hero-image.png
  text: For adults in North Lincolnshire (online UK‑wide available)
  title: Specialist neurodiversity assessments & formulations.
  subtitle: Independent, friendly, evidence‑based. Clear recommendations you can act on.

ctas:
  primary:
    text: Book a free 15‑minute consultation
    link: /consultation
    alt: Book a consultation
  secondary:
    text: See assessment options
    link: /services
    alt: View services
  deep:
    lead_text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
    text: Questions? Get in touch.
    link: /contact
    alt: Contact us

sections:
  how_it_works: How it works
  services: Services
  blog: Latest from the blog
  blog_subtitle: Lorem Ipsum
  faqs: Frequently Asked Questions

steps:
  - text: Free 15‑min consult → understand needs.
  - text: Assessment or formulation → structured sessions & validated tools.
  - text: Clear recommendations → practical, tailored next steps (work, study, life).

footer:
  title: Together Assessments
  business_info: Sole trader, trading as Together Assessments. North Lincolnshire and surrounding areas.
